### ISSUE TITLE
为什么无法连接电脑

### ISSUE THREAD

**Issue by a982246809** [plus1998/autoxjs-vite-vue#1]
![image](https://github.com/user-attachments/assets/5712317c-30be-497c-b0c2-c13f40bd168a)

**Comment by a982246809** [comment]
paramter specific as non-null ....

**Comment by plus1998** [comment]
抱歉，未在windows上运行过。
我估计是chokidar对路径监控的问题，不是websocket链接的问题，尝试在WSL上跑？

**Comment by plus1998** [comment]
刚刚在windows上测试通过了。没复现你的问题
<img width="748" alt="image" src="https://github.com/user-attachments/assets/66c50ded-9101-4ca9-a862-5957508f2b3b">

**Comment by a982246809** [comment]
请问你是autox 是哪个版本   我升级到最新的6.6了

**Comment by a982246809** [comment]
现在可以了  , 降到6.5的版本后 

这个地址有可以弄成动态的方法吗
![image](https://github.com/user-attachments/assets/6e54d925-93a5-4602-b648-a31ddc8a888c)

**Comment by plus1998** [comment]
> 现在可以了 , 降到6.5的版本后
> 
> 这个地址有可以弄成动态的方法吗 ![image](https://private-user-images.githubusercontent.com/56909676/355342285-6e54d925-93a5-4602-b648-a31ddc8a888c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mjk0MzYsIm5iZiI6MTcyMjkyOTEzNiwicGF0aCI6Ii81NjkwOTY3Ni8zNTUzNDIyODUtNmU1NGQ5MjUtOTNhNS00NjAyLWI2NDgtYTMxZGRjOGE4ODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NjdiZDEwYzI5MTRlNzg0NzAxOWE2ODc3MmQ1YzFjZjllNGI5MDJkYzdlNzcwNjU2NTZkMTIwNGM1NzExYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T2FzsijHIiW_ojhWCsjAcB4jKiZTpHNyiqA7_30Q3no)

没想到特别好的方案，随便做了一下，你可以重新拉一下代码

**Comment by a982246809** [comment]
![image](https://github.com/user-attachments/assets/3dfaaf37-1324-449c-bff4-97044285518c)
这个文件夹里面的代码改变  不会热更新的吗

**Comment by plus1998** [comment]
匹配的是 autox/**/*.ts
详细的可以自己修改或者测试一下

**Comment by a982246809** [comment]
可能代码已报错就不会热更新了
还想请教一下 ,
1 为什么在不同文件 声明相同的变量名会报重复声明
2 logger这个日志插件 , 我现在autox文件夹中全局都可以调用 , 要怎么做
3 我想做个自定义ui的悬浮窗 , 要怎么做? 可以用vue吗?

**Comment by plus1998** [comment]
> 可能代码已报错就不会热更新了 还想请教一下 , 1 为什么在不同文件 声明相同的变量名会报重复声明 2 logger这个日志插件 , 我现在autox文件夹中全局都可以调用 , 要怎么做 3 我想做个自定义ui的悬浮窗 , 要怎么做? 可以用vue吗?

1 这个估计是rhino的问题，正常写js也会这样
2 不理解你的问题
3 这个要你自己去想办法实现

目前这个issue太乱了，你可以去群里交流765354002。

**Comment by plus1998** [comment]
版本问题，暂时只支持到6.5.x
