### ISSUE TITLE
npm run build编译后，雷电或者mumu模拟器页面显示不出来

### ISSUE THREAD

**Issue by dfsfdfse** [plus1998/autoxjs-vite-vue#2]
npm run build编译后在 android studio的模拟器上能正常显示，但是用雷电或者mumu模拟器页面显示不出来,控制台也没有报错

**Comment by plus1998** [comment]
可能跟webview的版本有关，你可以试试更新模拟器里面的webview

**Comment by dfsfdfse** [comment]
我也知道可能是这个问题，但是如何更新模拟器的webview是个麻烦事

**Comment by plus1998** [comment]
有安装包的。。https://www.apkmirror.com/apk/google-inc/android-system-webview/
